# Generated by Django 3.2.13 on 2022-05-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vietnam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 날짜입니다.', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 날짜입니다.', verbose_name='수정 일시')),
                ('area', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
