# Generated by Django 3.2.13 on 2022-05-20 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietnam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vietnam',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vietnam',
            name='area',
            field=models.CharField(max_length=30),
        ),
    ]
